### ISSUE TITLE
A bug of any new blog

### ISSUE THREAD

**Issue by DuskXi** [auroral-ui/hexo-theme-aurora#105] opened 2021-05-24 15:06 UTC
I follow the document *https://aurora.tridiamond.tech/zh/guide/getting-started.html#%E4%BE%9D%E8%B5%96%E7%8E%AF%E5%A2%83* to install

But whatever I do any thing, the website also will look like:

![image](https://user-images.githubusercontent.com/84715902/119367078-2dafe680-bce4-11eb-9493-681e37974738.png)

and this is the console:

![image](https://user-images.githubusercontent.com/84715902/119367415-7ff10780-bce4-11eb-9bbd-602c2b7335b9.png)

I can't do anything, because it still not change.

And I can't find what I do wrong.

**Comment by guowei-gong** [comment] 2021-05-25 03:25
附议，我出现了同样的问题，这让我的配置是失效的。
我的 hexo version: 5.4.0；node version: 12.12.0

![image](https://user-images.githubusercontent.com/62499904/119434904-b615a200-bd4b-11eb-943f-9df119e04696.png)

**Comment by RivenNero** [comment] 2021-06-11 13:37
Me too.

**Comment by TriDiamond** [comment] 2021-06-12 00:03
I will take a look at this! Thanks for reporting.

**Comment by TriDiamond** [comment] 2021-06-24 03:34
Duplicate of #104

**Closed by TriDiamond** 2021-06-24 03:34 UTC
Labels: bug, in progress
